#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-morecane
Version  : 0.1.0
Release  : 3
URL      : https://rubygems.org/downloads/morecane-0.1.0.gem
Source0  : https://rubygems.org/downloads/morecane-0.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : ruby
BuildRequires : rubygem-cane
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
= Morecane
== What?
The cane gem provides a great framework for running quality checks over your
ruby project as part of continuous integration build. It comes with a few
checks out of the box, but also provides an API for loading custom checks.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n morecane-0.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-morecane.gemspec

%build
gem build rubygem-morecane.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
morecane-0.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/morecane-0.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/lib/morecane.rb
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/lib/morecane/encoding_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/lib/morecane/must_match_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/morecane-0.1.0/lib/morecane/must_not_match_check.rb
/usr/lib64/ruby/gems/2.3.0/specifications/morecane-0.1.0.gemspec
